kind: Secret
apiVersion: v1
metadata:
  name: postgres-secret
data:
  POSTGRES_DB: ZmVhc3Q=
  POSTGRES_PASSWORD: ZmVhc3Q=
  POSTGRES_USER: ZmVhc3Q=
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: feast-data-stores
data:
  postgres: aG9zdDogcG9zdGdyZXMuZmVhc3Quc3ZjLmNsdXN0ZXIubG9jYWwKcG9ydDogNTQzMgpkYXRhYmFzZTogJHtQT1NUR1JFU19EQn0KZGJfc2NoZW1hOiBwdWJsaWMKdXNlcjogJHtQT1NUR1JFU19VU0VSfQpwYXNzd29yZDogJHtQT1NUR1JFU19QQVNTV09SRH0=
  sql: cGF0aDogcG9zdGdyZXNxbCtwc3ljb3BnOi8vJHtQT1NUR1JFU19VU0VSfToke1BPU1RHUkVTX1BBU1NXT1JEfUBwb3N0Z3Jlcy5mZWFzdC5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyLyR7UE9TVEdSRVNfREJ9CmNhY2hlX3R0bF9zZWNvbmRzOiA2MApzcWxhbGNoZW15X2NvbmZpZ19rd2FyZ3M6CiAgZWNobzogZmFsc2UKICBwb29sX3ByZV9waW5nOiB0cnVl
type: Opaque
